booking/urls.py
from django.urls import path

from booking import views


app_name = "booking"

urlpatterns = [
    path("", views.home, name="home"),

    path("reserve/", views.userReserveTicketView, name='reserve'),

    path('delete/<int:pk>/', views.userDeleteTicketView, name='delete'),
]

club/urls.py
from django.urls import path

from club import views


app_name = "club"

urlpatterns = [
    path("faq/", views.seeQuestion, name='faq'),
    path("trains/", views.allTrain, name='tains'),
    path("rating/<str:pk>/", views.sendComment, name='rating'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('booking.urls')),

    path('user/', include("user.urls")),

    path('club/', include("club.urls")),
]

user/urls.py
from django.urls import path

from user import views


app_name = "user"

urlpatterns = [
    path("", views.loginUser, name='login'),
    path("profile/", views.userProfile, name='profile'),
    path("logout/", views.logoutUser, name='logout'),
    path("register/", views.registerUser, name='register'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user       = models.ForeignKey(User, on_delete=models.CASCADE)
    username   = models.CharField(max_length = 150)
    email      = models.EmailField(unique=True)
    first_name = models.CharField(max_length = 150)
    last_name  = models.CharField(max_length = 150)

    def __str__(self):
        return f"{self.username} with USER_ID {self.user}"

user/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class RegisterUser(UserCreationForm):
    password1 = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'••••••••••••'}))
    password2 = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'••••••••••••'}))

    class Meta:
        model = User
        fields = ['username','email','first_name','first_name']

        labels = {
            'password1': 'گذر واژه',
            'password2': 'تکرار گذر واژه',
        }

        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control my-5', 'placeholder':'example1234@gmail.com'}),
            'phone': forms.NumberInput(attrs={'class':'form-control my-5', 'placeholder':'09123456789'}),
            'username': forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'Username'}),
            'password1': forms.PasswordInput(attrs={'class':'form-control my-5', 'placeholder':'••••••••••••'}),
            'password2': forms.PasswordInput(attrs={'class':'form-control my-5', 'placeholder':'••••••••••••'}),
            'first_name': forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'Ali'}),
            'last_name': forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'alizadeh'}),
        }

    def clean(self) -> dict[str, Any]:
        cleaned_data = super(RegisterUser, self).clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 != password2:
            raise ValidationError("Passwords are not match!")


class LoginUser(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'Username'}))
    password = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control my-5', 'placeholder':'••••••••••••'}))

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth, messages

from user.models import Profile
from user.forms import RegisterUser, LoginUser
from booking.models import ReserveTicket


def logoutUser(request):
    auth.logout(request)
    messages.info(request, '')
    return redirect('booking:home')


def loginUser(request):
    if request.user.is_authenticated:
        return redirect("")
    elif request.method == "POST":
        form = LoginUser(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = auth.authenticate(request=request, username=username, password=password)
            if user is not None:
                auth.login(request, user=user)
                return redirect("booking:home")
            else:
                messages.error(request, "user not found")
                return redirect("user:login")
        else:
            messages.error(request, "Form is not valid")
            return redirect("user:login")
    else:
        form = LoginUser()
    return render(request, "user/login.html", {'form':form})


def registerUser(request):
    if request.user.is_authenticated:
        messages.warning(request, '')
        return redirect("booking:home")
    elif request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = User.objects.create_user(email=email, username=username, password=password1,first_name=first_name,
                                            last_name=last_name)
            user.set_password(password1)
            user.is_active = True
            user.save()
            messages.success(request, '')
            return redirect('user:login')
        else:
            messages.error(request, f'{form.errors}')
            return redirect('user:register')
    else:
        form = RegisterUser()
    return render(request, "user/register.html", {'form': form})


def userProfile(request):
    if request.user.is_authenticated:
        user = request.user
        t = ReserveTicket.objects.filter(user=user)
        p = Profile.objects.get(user=user)
        return render(request, "user/profile.html", {'profile':p,'ticket':t})
    else:
        messages.info(request, "")
        return redirect("user:login")

templates/user/login.html
{% extends 'root.html' %}

{% block title %}
    Login
{% endblock title %}

{% block doc %}
<section class="h-80 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
  
                  <form action="{% url 'user:login' %}" method="post">
                    <p>Please login to your account</p>
  
                    {{form.as_p}}

                    <div class="pt-1 mb-5 pb-1">
                        <p style="display: inline;">
                            Don't have an account :
                        </p>
                        <a class="text-muted" href="{% url 'user:register' %}">
                            Register
                        </a>
                    </div>

                    {% csrf_token %}
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                        <input type="submit" value="submit">
                    </div>
  
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock doc %}

templates/user/profile.html
{% extends 'root.html' %}

{% block title %}
    Profile
{% endblock title %}

{% block doc %}
    <p>
        user profile : {{profile.username}}
    </p>

    
    {% for obj in ticket %}
        <h1>
            <a href="{% url 'booking:delete' obj.pk %}">
                {{obj.user.username}}
            </a>
        </h1>
    {% endfor %}


{% endblock doc %}

templates/user/register.html
{% extends 'root.html' %}

{% block title %}
    Login
{% endblock title %}

{% block doc %}
<section class="h-80 gradient-form" style="background-color: #eee;">
    <div class="container py-5">
      <div class="row d-flex justify-content-center align-items-center">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6">
                <div class="card-body p-md-5 mx-md-4">
  
                  <form action="{% url 'user:register' %}" method="post">
                    <p>Please register your account</p>
  
                    {{form.as_p}}

                    <div class="pt-1 mb-5 pb-1">
                        <p style="display: inline;">
                            Already have an account :
                        </p>
                        <a class="text-muted" href="{% url 'user:login' %}">
                            Login
                        </a>
                    </div>

                    {% csrf_token %}
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                        <input type="submit" value="submit">
                    </div>
  
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock doc %}